---
# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:remerge/template
project_id: ansible-role-zfs
project_license: apache-2.0
project_name: Ansible Role for ZFS
project_owner: core
project_type: ansible-role
use_python: true
