---
default_stages:
  - commit

default_install_hook_types:
  - commit-msg
  - pre-commit
  - prepare-commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        exclude: "^project/"

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.32.2"
    hooks:
      - id: markdownlint-fix
        name: markdownlint

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.28.0"
    hooks:
      - id: yamllint
        entry: yamllint --strict

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: "v2.1.0"
    hooks:
      - id: shell-fmt-go

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.8.0.4"
    hooks:
      - id: shellcheck

  - repo: https://github.com/hollow/pre-commit-actionlint
    rev: "v1.6.22"
    hooks:
      - id: actionlint

  - repo: https://github.com/ansible/ansible-lint
    rev: "v6.9.0"
    hooks:
      - id: ansible-lint
        name: ansible-lint

  - repo: https://github.com/robertdebock/pre-commit
    rev: "v1.5.2"
    hooks:
      - id: ansible_role_find_empty_directories
      - id: ansible_role_find_empty_files
      - id: ansible_role_find_horizontal_when
      - id: ansible_role_find_undefined_handlers
      - id: ansible_role_find_unquoted_values
      - id: ansible_role_find_unused_variable
      - id: ansible_role_fix_readability

  - repo: https://github.com/bridgecrewio/checkov
    rev: "2.2.106"
    hooks:
      - id: checkov
        name: checkov
        args: [--config-file=.checkov.yml]

  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.18.0"
    hooks:
      - id: gitlint
